export const ADD_NUMBER = "ADD_NUMBER";
export const SUB_NUMBER = "SUB_NUMBER";
export const ADD_NULLNUMBER = "ADD_NULLNUMBER";

export const CHANGE_BANNERS = "CHANGE_BANNERS";
export const CHANGE_RECOMMENDS = "CHANGE_RECOMMENDS";

export const FETCH_HOME_MUTLIDATA = "FETCH_HOME_MUTLIDATA"